"""changed some constraints

Revision ID: 484596214cd9
Revises: a9250f79b6d0
Create Date: 2024-02-03 23:33:13.864263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484596214cd9'
down_revision = 'a9250f79b6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beehive', schema=None) as batch_op:
        batch_op.drop_column('devicename')
        batch_op.add_column(sa.Column('device', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beehive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devicename', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('device')

    # ### end Alembic commands ###
