"""Fixed relationship issue

Revision ID: 2da0004382fb
Revises: 25c0a2762e37
Create Date: 2024-01-27 22:30:00.340747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da0004382fb'
down_revision = '25c0a2762e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userbeehive', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_userbeehive_user', 'user', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('fk_userbeehive_beehive', 'beehive', ['device_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userbeehive', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'beehive', ['device_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
