"""added banned column to role

Revision ID: 469e86f98f13
Revises: 71fd70be07c9
Create Date: 2024-02-08 14:42:01.916308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469e86f98f13'
down_revision = '71fd70be07c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('banned', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('banned')

    # ### end Alembic commands ###
