"""added foreign key to user

Revision ID: 77ed8a276b76
Revises: 3d4876aad584
Create Date: 2024-02-08 13:52:43.554850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ed8a276b76'
down_revision = '3d4876aad584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.String(length=32), nullable=False))
        batch_op.create_foreign_key("fk_user_role", 'role', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_role", type_='foreignkey')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###
