"""Initial migration

Revision ID: 7bef157908c7
Revises: 
Create Date: 2024-01-27 20:06:03.949134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bef157908c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beehive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devicename', sa.String(length=50), nullable=True),
    sa.Column('displayname', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('devicename')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('userbeehive',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['beehive.id'], "fk_userbeehive_beehive"),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], "fk_userbeehive_user"),
    sa.PrimaryKeyConstraint('user_id', 'device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userbeehive')
    op.drop_table('user')
    op.drop_table('beehive')
    # ### end Alembic commands ###
