"""changed some constraints

Revision ID: 9298d4eee6ec
Revises: a9250f79b6d0
Create Date: 2024-02-03 23:53:11.226258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9298d4eee6ec'
down_revision = 'a9250f79b6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_beehive')
    with op.batch_alter_table('beehive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device', sa.String(length=32), nullable=False))
        batch_op.drop_column('devicename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beehive', schema=None) as batch_op:
        batch_op.add_column(sa.Column('devicename', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('device')

    op.create_table('_alembic_tmp_beehive',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('device', sa.VARCHAR(length=32), nullable=False),
    sa.Column('displayname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('apiary_id', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['apiary_id'], ['apiary.id'], name='fk_beehive_apiary'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
