"""added apiary measurement and beehive measurements

Revision ID: a9250f79b6d0
Revises: 817680774b70
Create Date: 2024-02-02 15:52:06.676072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9250f79b6d0'
down_revision = '817680774b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apiary_measurement',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('humidity', sa.Numeric(), nullable=True),
    sa.Column('air_pressure', sa.Numeric(), nullable=True),
    sa.Column('apiary_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['apiary_id'], ['apiary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beehive_measurement',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Numeric(), nullable=True),
    sa.Column('humidity', sa.Numeric(), nullable=True),
    sa.Column('air_pressure', sa.Numeric(), nullable=True),
    sa.Column('weight', sa.Numeric(), nullable=True),
    sa.Column('food_remaining', sa.Numeric(), nullable=True),
    sa.Column('beehive_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['beehive_id'], ['beehive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('measurement')
    with op.batch_alter_table('apiary', schema=None) as batch_op:
        batch_op.drop_column('humidity')
        batch_op.drop_column('air_pressure')
        batch_op.drop_column('temperature')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=345),
               type_=sa.String(length=254),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=254),
               type_=sa.VARCHAR(length=345),
               existing_nullable=False)

    with op.batch_alter_table('apiary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.NUMERIC(), nullable=True))
        batch_op.add_column(sa.Column('air_pressure', sa.NUMERIC(), nullable=True))
        batch_op.add_column(sa.Column('humidity', sa.NUMERIC(), nullable=True))

    op.create_table('measurement',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=False),
    sa.Column('temperature', sa.NUMERIC(), nullable=True),
    sa.Column('humidity', sa.NUMERIC(), nullable=True),
    sa.Column('air_pressure', sa.NUMERIC(), nullable=True),
    sa.Column('weight', sa.NUMERIC(), nullable=True),
    sa.Column('food_remaining', sa.NUMERIC(), nullable=True),
    sa.Column('beehive_id', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['beehive_id'], ['beehive.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('beehive_measurement')
    op.drop_table('apiary_measurement')
    # ### end Alembic commands ###
