"""Added constraints

Revision ID: e15c02a1c46f
Revises: 7bef157908c7
Create Date: 2024-01-27 20:07:28.396276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15c02a1c46f'
down_revision = '7bef157908c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userbeehive', schema=None) as batch_op:
        batch_op.drop_constraint("fk_userbeehive_user", type_='foreignkey')
        batch_op.drop_constraint("fk_userbeehive_beehive", type_='foreignkey')
        batch_op.create_foreign_key("fk_userbeehive_user", 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key("fk_userbeehive_beehive", 'beehive', ['device_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userbeehive', schema=None) as batch_op:
        batch_op.drop_constraint("fk_userbeehive_beehive", type_='foreignkey')
        batch_op.drop_constraint("fk_userbeehive_user", type_='foreignkey')
        batch_op.create_foreign_key("fk_userbeehive_beehive", 'beehive', ['device_id'], ['id'])
        batch_op.create_foreign_key("fk_userbeehive_user", 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
